version: "3.7"
services:
  web5:
    stop_grace_period: 60s
    deploy:
      resources:
        limits:
          cpus: '3'
          memory: 3G
        reservations:
          cpus: '0.5'
          #memory: 2G
    build: .
    image: ${IMG_SQLSERVER2022K8S}
    volumes:
      - "f:/databases/example/data:d:"
      - "f:/databases/example/backup:e:"
      - "f:/databases/example/control:c:/SQLControl"
      - "c:/windows/temp:f:"
    networks:
      - container_default
    environment:
      - MSSQL_ADMIN_USERNAME=sa
      - MSSQL_ADMIN_PWD=sapwd
      - MSSQL_DATABASE=mydatabase
      - MSSQL_LIFECYCLE=ATTACH
      - MSSQL_SPCONFIGURE=max degree of parallelism:1;backup compression default:1
      - MSSQL_SPCONFIGURERESTART=0
      - MSSQL_PATH_DATA=d:\data
      - MSSQL_PATH_LOG=d:\log
      - MSSQL_PATH_BACKUP=e:\backup
      - MSSQL_PATH_CONTROL=c:\SQLControl
      - SBS_TEMPORARY=f:\
      - SBS_ENTRYPOINTERRORACTION=Stop
networks:
  container_default:
    external: true
