version: "3.7"
services:
  web:
    stop_grace_period: 40s
    build: .
    image: ${CONTAINERREGISTRY}/sqlserver2022base:1.0-beta2
    volumes:
      - "f:/databases/example/data:d:"
    networks:
      - container_default
    environment:
      - MSSQL_ADMIN_USERNAME=sa
      - MSSQL_ADMIN_PWD=sapwd
      - MSSQL_PATH_DATA=d:\data
      - MSSQL_PATH_LOG=d:\log
      - MSSQL_PATH_SYSTEM=d:\system
      - MSSQL_PATH_BACKUP=d:\backup
      - SBS_ENTRYPOINTERRORACTION=Stop
networks:
  container_default:
    external: true
